"""Propagate Sanya tri-static fit covariance to heliocentric orbit elements.

This script is intended to run in the conda environment that provides dasst:

    conda run -n rebound python estimate_orbit_element_uncertainty.py

The input fit product is generated by fit_all_ballistic_snr_weighted.py.  Each
event covariance is sampled in the fitted GCRS state and log10(C_D A/m), moved
backward to a configurable above-atmosphere altitude, transformed to ITRS, and
passed to dasst.orbit_determination.rebound_od for solar-system propagation.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
from dataclasses import dataclass

import h5py
import matplotlib.pyplot as plt
import numpy as np
from astropy import units as u
from astropy.coordinates import CartesianDifferential, CartesianRepresentation, GCRS, ITRS
from astropy.time import Time, TimeDelta
from scipy.integrate import solve_ivp

import dasst


INPUT_H5 = "results/all_tristatic_ballistic_snr_weighted_v20260613b.h5"
OUTPUT_H5 = "results/orbit_element_uncertainty_v20260614a.h5"
SUMMARY_CSV = "results/orbit_element_uncertainty_summary_v20260614a.csv"
ARTICLE_TABLE = "/Users/jvi019/src/sanya_tristatic_paper/tables/orbit_element_uncertainty_summary.tex"
EXAMPLE_FIGURE = "/Users/jvi019/src/sanya_tristatic_paper/figures/orbit_uncertainty_example.pdf"
ORBIT_XY_FIGURE = "/Users/jvi019/src/sanya_tristatic_paper/figures/orbit_xy_sanya_example.pdf"

DEFAULT_KERNEL = "/Users/jvi019/src/rebound_examples/data/de430.bsp"

EARTH_MU_M3_S2 = 3.986004418e14
EARTH_RADIUS_M = 6371.0e3
EARTH_OMEGA_RAD_S = 7.2921150e-5
AU_M = 149597870700.0
MIN_B = 1e-4
MAX_B = 1e3


@dataclass
class EventFit:
    event_id: str
    epoch: Time
    params: np.ndarray
    covariance: np.ndarray
    covariance_available: bool
    n_points: int
    rms_total_path_residual_m: float
    median_sanya_snr_db: float
    median_all_snr_db: float


def decode(value) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if hasattr(value, "decode"):
        return value.decode("utf-8")
    return str(value)


def load_fits(path: str) -> list[EventFit]:
    fits: list[EventFit] = []
    with h5py.File(path, "r") as h:
        event_ids = [decode(x) for x in h["event_id"][:]]
        n_points = h["n_points"][:]
        rms = h["rms_total_path_residual_m"][:]
        points = h["points"]
        for idx, event_id in enumerate(event_ids):
            group = points[event_id]
            cov = group["parameter_covariance"][:]
            params = group["params"][:]
            fits.append(
                EventFit(
                    event_id=event_id,
                    epoch=Time(float(group["time_ns"][0]) / 1e9, format="unix", scale="utc"),
                    params=params,
                    covariance=cov,
                    covariance_available=bool(group.attrs.get("covariance_available", False)),
                    n_points=int(n_points[idx]),
                    rms_total_path_residual_m=float(rms[idx]),
                    median_sanya_snr_db=float(np.nanmedian(group["snr_db"][:, 0])),
                    median_all_snr_db=float(np.nanmedian(group["snr_db"][:])),
                )
            )
    return fits


def regularized_covariance(cov: np.ndarray) -> np.ndarray:
    cov = 0.5 * (np.asarray(cov, dtype=np.float64) + np.asarray(cov, dtype=np.float64).T)
    if not np.all(np.isfinite(cov)):
        raise ValueError("non-finite covariance")
    eigval, eigvec = np.linalg.eigh(cov)
    scale = max(float(np.nanmax(np.diag(cov))), 1.0)
    eigval = np.maximum(eigval, scale * 1e-12)
    return (eigvec * eigval) @ eigvec.T


def sample_parameters(fit: EventFit, n_samples: int, rng: np.random.Generator) -> np.ndarray:
    if n_samples == 1:
        return fit.params[None, :]
    cov = regularized_covariance(fit.covariance)
    samples = rng.multivariate_normal(fit.params, cov, size=n_samples)
    samples[:, 6] = np.clip(samples[:, 6], math.log10(MIN_B), math.log10(MAX_B))
    samples[0, :] = fit.params
    return samples


def exponential_density(alt_m: float) -> float:
    """Simple high-atmosphere density model used only for backward drag removal."""
    alt_km = np.clip(alt_m / 1e3, 70.0, 160.0)
    rho_100 = 5.0e-7
    scale_height_km = 7.0
    return float(rho_100 * np.exp(-(alt_km - 100.0) / scale_height_km))


def propagate_to_above_atmosphere(
    params: np.ndarray,
    target_alt_km: float,
    max_back_s: float,
    include_drag: bool = True,
) -> tuple[np.ndarray, float, bool]:
    """Integrate the fitted geocentric state backward to target altitude."""
    b_drag = float(np.clip(10.0 ** params[6], MIN_B, MAX_B)) if include_drag else 0.0
    y0 = np.asarray(params[:6], dtype=np.float64)

    if np.linalg.norm(y0[:3]) - EARTH_RADIUS_M >= target_alt_km * 1e3:
        return y0.copy(), 0.0, True

    omega_vec = np.array([0.0, 0.0, EARTH_OMEGA_RAD_S], dtype=np.float64)

    def deriv(_t, y):
        r = y[:3]
        v = y[3:]
        radius = max(float(np.linalg.norm(r)), 1.0)
        alt = radius - EARTH_RADIUS_M
        gravity = -EARTH_MU_M3_S2 * r / radius**3
        v_rel = v - np.cross(omega_vec, r)
        drag = -b_drag * exponential_density(alt) * float(np.linalg.norm(v_rel)) * v_rel
        return np.concatenate([v, gravity + drag])

    def event_alt(_t, y):
        return float(np.linalg.norm(y[:3]) - EARTH_RADIUS_M - target_alt_km * 1e3)

    event_alt.terminal = True
    event_alt.direction = 0

    sol = solve_ivp(
        deriv,
        (0.0, -float(max_back_s)),
        y0,
        events=event_alt,
        rtol=1e-8,
        atol=np.array([0.01, 0.01, 0.01, 1e-4, 1e-4, 1e-4]),
        max_step=0.05,
    )
    reached = len(sol.t_events[0]) > 0
    return sol.y[:, -1].astype(np.float64), float(sol.t[-1]), bool(reached)


def gcrs_to_itrs_state(state_gcrs: np.ndarray, epoch: Time) -> np.ndarray:
    rep = CartesianRepresentation(
        state_gcrs[0] * u.m,
        state_gcrs[1] * u.m,
        state_gcrs[2] * u.m,
        differentials=CartesianDifferential(
            state_gcrs[3] * u.m / u.s,
            state_gcrs[4] * u.m / u.s,
            state_gcrs[5] * u.m / u.s,
        ),
    )
    itrs = GCRS(rep, obstime=epoch).transform_to(ITRS(obstime=epoch))
    pos = itrs.cartesian.without_differentials().xyz.to_value(u.m)
    vel = itrs.cartesian.differentials["s"].d_xyz.to_value(u.m / u.s)
    return np.concatenate([pos, vel])


def circular_std_deg(values_deg: np.ndarray) -> float:
    vals = np.deg2rad(np.asarray(values_deg, dtype=np.float64))
    center = np.angle(np.nanmean(np.exp(1j * vals)))
    delta = (vals - center + np.pi) % (2.0 * np.pi) - np.pi
    return float(np.rad2deg(np.nanstd(delta, ddof=1)))


def summarize_kepler(kepler: np.ndarray) -> dict[str, float]:
    # pyorb order used by dasst: a, e, i, omega, Omega, true anomaly.
    a_au = kepler[0, :] / AU_M
    e = kepler[1, :]
    inc = kepler[2, :]
    argp = kepler[3, :]
    node = kepler[4, :]
    nu = kepler[5, :]
    return {
        "a_au_mean": float(np.nanmean(a_au)),
        "a_au_std": float(np.nanstd(a_au, ddof=1)),
        "e_mean": float(np.nanmean(e)),
        "e_std": float(np.nanstd(e, ddof=1)),
        "e_p05": float(np.nanpercentile(e, 5.0)),
        "e_p50": float(np.nanpercentile(e, 50.0)),
        "e_p95": float(np.nanpercentile(e, 95.0)),
        "interstellar_fraction_e_gt_1": float(np.nanmean(e > 1.0)),
        "inc_deg_mean": float(np.nanmean(inc)),
        "inc_deg_std": circular_std_deg(inc),
        "argp_deg_std": circular_std_deg(argp),
        "node_deg_std": circular_std_deg(node),
        "nu_deg_std": circular_std_deg(nu),
    }


def above_atmosphere_state_diagnostics(
    drag_states: np.ndarray,
    no_drag_states: np.ndarray,
) -> dict[str, float]:
    drag_states = np.asarray(drag_states, dtype=np.float64)
    no_drag_states = np.asarray(no_drag_states, dtype=np.float64)
    speed_drag = np.linalg.norm(drag_states[:, 3:], axis=1)
    speed_no_drag = np.linalg.norm(no_drag_states[:, 3:], axis=1)
    pos_frac = np.linalg.norm(drag_states[:, :3] - no_drag_states[:, :3], axis=1) / np.linalg.norm(
        no_drag_states[:, :3], axis=1
    )
    vel_frac = np.linalg.norm(drag_states[:, 3:] - no_drag_states[:, 3:], axis=1) / speed_no_drag
    speed_frac = np.abs(speed_drag - speed_no_drag) / speed_no_drag
    return {
        "pre_atmosphere_speed_drag_m_s_median": float(np.nanmedian(speed_drag)),
        "pre_atmosphere_speed_no_drag_m_s_median": float(np.nanmedian(speed_no_drag)),
        "pre_atmosphere_speed_delta_m_s_median": float(np.nanmedian(speed_drag - speed_no_drag)),
        "pre_atmosphere_speed_frac_diff_median": float(np.nanmedian(speed_frac)),
        "pre_atmosphere_velocity_vector_frac_diff_median": float(np.nanmedian(vel_frac)),
        "pre_atmosphere_position_frac_diff_median": float(np.nanmedian(pos_frac)),
        "pre_atmosphere_state_reliability_flag": bool(np.nanmedian(vel_frac) > 0.10),
    }


def process_event(fit: EventFit, args, rng: np.random.Generator) -> dict[str, float | str | int | bool | np.ndarray]:
    samples = sample_parameters(fit, args.samples, rng)
    itrs_states = []
    above_states_gcrs = []
    above_states_no_drag_gcrs = []
    epochs = []
    exit_dt = []
    exit_dt_no_drag = []
    reached = []
    reached_no_drag = []
    for params in samples:
        state_above, dt_s, ok = propagate_to_above_atmosphere(
            params,
            args.above_atmosphere_alt_km,
            args.max_back_s,
            include_drag=True,
        )
        state_above_no_drag, dt_no_drag_s, ok_no_drag = propagate_to_above_atmosphere(
            params,
            args.above_atmosphere_alt_km,
            args.max_back_s,
            include_drag=False,
        )
        epoch_above = fit.epoch + TimeDelta(dt_s, format="sec")
        above_states_gcrs.append(state_above)
        above_states_no_drag_gcrs.append(state_above_no_drag)
        itrs_states.append(gcrs_to_itrs_state(state_above, epoch_above))
        epochs.append(epoch_above)
        exit_dt.append(dt_s)
        exit_dt_no_drag.append(dt_no_drag_s)
        reached.append(ok)
        reached_no_drag.append(ok_no_drag)

    # dasst expects one epoch.  The above-atmosphere propagation time spread is
    # normally small, so use the nominal-sample epoch for the batch.
    epoch = epochs[0]
    states = np.asarray(itrs_states, dtype=np.float64).T
    od = dasst.orbit_determination.rebound_od(
        states,
        epoch,
        args.kernel,
        kepler_out_frame=["HeliocentricMeanEcliptic"],
        radiant_out_frame=["GCRS", "GeocentricMeanEcliptic"],
        termination_check=True,
        dt=args.rebound_dt_s,
        max_t=args.rebound_max_t_s,
        progress_bar=False,
    )
    kepler = od["kepler_HeliocentricMeanEcliptic"][:, -1, :]
    summary = summarize_kepler(kepler)
    drag_diagnostics = above_atmosphere_state_diagnostics(
        np.asarray(above_states_gcrs, dtype=np.float64),
        np.asarray(above_states_no_drag_gcrs, dtype=np.float64),
    )
    summary.update(
        {
            "event_id": fit.event_id,
            "n_points": fit.n_points,
            "n_samples": int(args.samples),
            "rms_total_path_residual_m": fit.rms_total_path_residual_m,
            "median_sanya_snr_db": fit.median_sanya_snr_db,
            "median_all_snr_db": fit.median_all_snr_db,
            "first_detection_alt_km": float(np.linalg.norm(fit.params[:3]) - EARTH_RADIUS_M) / 1e3,
            "above_atmosphere_epoch_unix": float(epoch.unix),
            "above_atmosphere_dt_s_median": float(np.nanmedian(exit_dt)),
            "above_atmosphere_no_drag_dt_s_median": float(np.nanmedian(exit_dt_no_drag)),
            "above_atmosphere_reached_fraction": float(np.mean(reached)),
            "above_atmosphere_no_drag_reached_fraction": float(np.mean(reached_no_drag)),
            "covariance_available": bool(fit.covariance_available),
            "kepler_sample": kepler,
            "above_states_gcrs": np.asarray(above_states_gcrs, dtype=np.float64),
            "above_states_no_drag_gcrs": np.asarray(above_states_no_drag_gcrs, dtype=np.float64),
        }
    )
    summary.update(drag_diagnostics)
    return summary


def rotation_matrix_313(node_deg: float, inc_deg: float, argp_deg: float) -> np.ndarray:
    node = np.deg2rad(node_deg)
    inc = np.deg2rad(inc_deg)
    argp = np.deg2rad(argp_deg)
    cn, sn = np.cos(node), np.sin(node)
    ci, si = np.cos(inc), np.sin(inc)
    cw, sw = np.cos(argp), np.sin(argp)
    rz_node = np.array([[cn, -sn, 0.0], [sn, cn, 0.0], [0.0, 0.0, 1.0]])
    rx_inc = np.array([[1.0, 0.0, 0.0], [0.0, ci, -si], [0.0, si, ci]])
    rz_argp = np.array([[cw, -sw, 0.0], [sw, cw, 0.0], [0.0, 0.0, 1.0]])
    return rz_node @ rx_inc @ rz_argp


def ellipse_xy_from_kepler(kep: np.ndarray, n_points: int = 360) -> tuple[np.ndarray, np.ndarray] | None:
    a_m, e, inc_deg, argp_deg, node_deg, _nu_deg = [float(x) for x in kep]
    if not np.isfinite(a_m) or not np.isfinite(e) or e >= 1.0 or e < 0.0 or a_m <= 0.0:
        return None
    true_anom = np.linspace(0.0, 2.0 * np.pi, n_points)
    p = a_m * (1.0 - e**2.0)
    r = p / (1.0 + e * np.cos(true_anom))
    perifocal = np.vstack([r * np.cos(true_anom), r * np.sin(true_anom), np.zeros_like(r)])
    ecliptic = rotation_matrix_313(node_deg, inc_deg, argp_deg) @ perifocal
    return ecliptic[0] / AU_M, ecliptic[1] / AU_M


def make_example_plot(row: dict, path: str, max_orbits: int = 40) -> None:
    kepler = np.asarray(row["kepler_sample"], dtype=np.float64)
    above = np.asarray(row["above_states_gcrs"], dtype=np.float64)
    a_au = kepler[0, :] / AU_M
    e = kepler[1, :]
    inc = kepler[2, :]

    nominal_pos = above[0, :3]
    nominal_vel = above[0, 3:]
    along = nominal_vel / np.linalg.norm(nominal_vel)
    radial = nominal_pos / np.linalg.norm(nominal_pos)
    cross = radial - np.dot(radial, along) * along
    cross /= np.linalg.norm(cross)
    normal = np.cross(along, cross)
    delta = above[:, :3] - nominal_pos[None, :]
    sample_along_m = delta @ along
    sample_cross_m = delta @ cross
    sample_normal_m = delta @ normal

    plt.rcParams.update(
        {
            "font.size": 11,
            "axes.labelsize": 11,
            "axes.titlesize": 12,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
        }
    )
    fig, axes = plt.subplots(2, 2, figsize=(9.2, 7.4), constrained_layout=True)
    ax = axes[0, 0]
    sc = ax.scatter(sample_along_m, sample_cross_m, c=sample_normal_m, s=18, cmap="coolwarm", alpha=0.85)
    ax.scatter([0.0], [0.0], marker="+", s=90, color="black", linewidths=1.4)
    ax.set_xlabel("Along-track offset at 200 km (m)")
    ax.set_ylabel("Cross-track offset at 200 km (m)")
    ax.set_title("Sampled above-atmosphere state")
    cb = fig.colorbar(sc, ax=ax, pad=0.01)
    cb.set_label("Normal offset (m)")

    ax = axes[0, 1]
    count = 0
    for idx in range(kepler.shape[1]):
        xy = ellipse_xy_from_kepler(kepler[:, idx])
        if xy is None:
            continue
        ax.plot(xy[0], xy[1], color="#3465a4", alpha=0.16, lw=0.8)
        count += 1
        if count >= max_orbits:
            break
    ax.scatter([0.0], [0.0], marker="o", s=35, color="#f5c542", edgecolor="black", linewidth=0.5, zorder=3)
    ax.set_aspect("equal", adjustable="box")
    lim = np.nanpercentile(np.abs(a_au[np.isfinite(a_au)]), 90) * 1.35 if np.any(np.isfinite(a_au)) else 2.0
    lim = float(np.clip(lim, 0.5, 5.0))
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_xlabel("Ecliptic x (AU)")
    ax.set_ylabel("Ecliptic y (AU)")
    ax.set_title("Heliocentric orbit samples")

    ax = axes[1, 0]
    ax.scatter(a_au, e, c=inc, s=20, cmap="viridis", alpha=0.8)
    ax.axhline(1.0, color="black", lw=1.0, ls="--")
    ax.set_xlabel("Semi-major axis (AU)")
    ax.set_ylabel("Eccentricity")
    ax.set_title("Element covariance sample")

    ax = axes[1, 1]
    ax.hist(e[np.isfinite(e)], bins=24, color="#4c72b0", alpha=0.8)
    ax.axvline(1.0, color="black", lw=1.0, ls="--")
    ax.set_xlabel("Eccentricity")
    ax.set_ylabel("Samples")
    ax.set_title("Interstellar boundary")

    fig.suptitle(
        f"{row['event_id']}: {int(row['n_samples'])} covariance samples, "
        f"{float(row['above_atmosphere_reached_fraction']):.2f} reached altitude cut"
    )
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path)
    fig.savefig(os.path.splitext(path)[0] + ".png", dpi=220)
    plt.close(fig)


def make_snr_scatter_plot(rows: list[dict], path: str) -> None:
    snr = np.asarray([r["median_sanya_snr_db"] for r in rows], dtype=np.float64)
    all_snr = np.asarray([r["median_all_snr_db"] for r in rows], dtype=np.float64)
    n_points = np.asarray([r["n_points"] for r in rows], dtype=np.float64)
    metrics = [
        ("a_au_std", r"$\sigma_a$ (AU)"),
        ("e_std", r"$\sigma_e$"),
        ("inc_deg_std", r"$\sigma_i$ (deg)"),
        ("argp_deg_std", r"$\sigma_\omega$ (deg)"),
        ("node_deg_std", r"$\sigma_\Omega$ (deg)"),
        ("nu_deg_std", r"$\sigma_\nu$ (deg)"),
    ]
    plt.rcParams.update(
        {
            "font.size": 11,
            "axes.labelsize": 11,
            "axes.titlesize": 11,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
        }
    )
    fig, axes = plt.subplots(2, 3, figsize=(11.0, 6.8), constrained_layout=True, sharex=True)
    for ax, (key, label) in zip(axes.flat, metrics):
        y = np.asarray([r[key] for r in rows], dtype=np.float64)
        good = np.isfinite(snr) & np.isfinite(y) & (y > 0)
        sc = ax.scatter(
            snr[good],
            y[good],
            c=all_snr[good],
            s=14.0 + 1.2 * np.clip(n_points[good], 0, 50),
            cmap="viridis",
            alpha=0.78,
            edgecolors="none",
        )
        ax.set_yscale("log")
        ax.set_ylabel(label)
        ax.grid(alpha=0.22, lw=0.5)
    for ax in axes[-1, :]:
        ax.set_xlabel("Median Sanya SNR (dB)")
    cb = fig.colorbar(sc, ax=axes, shrink=0.94, pad=0.015)
    cb.set_label("Median all-link SNR (dB)")
    fig.suptitle("Orbital-element uncertainty versus event SNR")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path)
    fig.savefig(os.path.splitext(path)[0] + ".png", dpi=220)
    plt.close(fig)


def kepler_text(kepler: np.ndarray) -> str:
    a_au = kepler[0, :] / AU_M
    e = kepler[1, :]
    inc = kepler[2, :]
    argp = kepler[3, :]
    node = kepler[4, :]
    nu = kepler[5, :]
    q = a_au * (1.0 - e)
    Q = a_au * (1.0 + e)
    a_j = 5.204
    with np.errstate(invalid="ignore"):
        tj = a_j / a_au + 2.0 * np.cos(np.deg2rad(inc)) * np.sqrt((a_au / a_j) * (1.0 - e**2.0))
    values = [
        ("a", a_au, "AU", 2),
        ("q", q, "AU", 3),
        ("Q", Q, "AU", 2),
        ("e", e, "", 3),
        ("i", inc, "deg", 1),
        ("T_J", tj, "", 2),
        (r"\omega", argp, "deg", 1),
        (r"\Omega", node, "deg", 4),
        (r"\nu", nu, "deg", 1),
    ]
    lines = ["Keplerian elements"]
    for name, arr, unit, ndigits in values:
        finite = np.asarray(arr, dtype=np.float64)
        mu = float(np.nanmean(finite))
        sig = circular_std_deg(finite) if unit == "deg" else float(np.nanstd(finite, ddof=1))
        fmt = f"{{:.{ndigits}f}}"
        suffix = f" {unit}" if unit else ""
        lines.append(f"${name}$ = {fmt.format(mu)} +/- {fmt.format(sig)}{suffix}")
    return "\n".join(lines)


def draw_planets(ax) -> None:
    planets = [
        ("Mercury", 0.387, "#999999"),
        ("Venus", 0.723, "#b79a74"),
        ("Earth", 1.000, "#5b8fc9"),
        ("Mars", 1.524, "#c7705f"),
        ("Jupiter", 5.204, "#9b8565"),
    ]
    theta = np.linspace(0.0, 2.0 * np.pi, 720)
    for name, radius, color in planets:
        ax.plot(radius * np.cos(theta), radius * np.sin(theta), color=color, lw=1.15, alpha=0.85, label=name)
        ax.scatter([radius], [0.0], color=color, s=38, zorder=3)
    ax.scatter([0.0], [0.0], s=140, color="#ffd21f", edgecolor="#333333", linewidth=1.0, zorder=4, label="Sun")


def make_orbit_xy_plot(row: dict, path: str, max_orbits: int = 300) -> None:
    kepler = np.asarray(row["kepler_sample"], dtype=np.float64)
    plt.rcParams.update(
        {
            "font.size": 15,
            "axes.labelsize": 21,
            "xtick.labelsize": 14,
            "ytick.labelsize": 14,
            "legend.fontsize": 14,
        }
    )
    fig, ax = plt.subplots(figsize=(8.6, 8.6), constrained_layout=True)
    draw_planets(ax)

    plotted = 0
    for idx in range(1, kepler.shape[1]):
        xy = ellipse_xy_from_kepler(kepler[:, idx])
        if xy is None:
            continue
        ax.plot(xy[0], xy[1], color="0.25", alpha=0.045, lw=0.8)
        plotted += 1
        if plotted >= max_orbits:
            break
    nominal_xy = ellipse_xy_from_kepler(kepler[:, 0])
    if nominal_xy is not None:
        ax.plot(nominal_xy[0], nominal_xy[1], color="0.15", alpha=0.9, lw=2.2, label="Nominal Sanya orbit")

    ax.text(
        0.04,
        0.05,
        kepler_text(kepler),
        transform=ax.transAxes,
        ha="left",
        va="bottom",
        fontsize=16,
        bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.72, "pad": 4},
    )
    ax.text(
        0.98,
        0.02,
        f"{row['event_id']}; n={int(row['n_samples'])}; alt={200:.0f} km",
        transform=ax.transAxes,
        ha="right",
        va="bottom",
        fontsize=11,
        color="0.45",
    )
    ax.set_xlim(-8.0, 8.0)
    ax.set_ylim(-8.0, 8.0)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("Heliocentric ecliptic x (AU)")
    ax.set_ylabel("Heliocentric ecliptic y (AU)")
    ax.grid(color="0.90", lw=0.8)
    ax.legend(loc="upper center", ncol=2, framealpha=0.9)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path)
    fig.savefig(os.path.splitext(path)[0] + ".png", dpi=220)
    plt.close(fig)


def write_summary_csv(path: str, rows: list[dict]) -> None:
    fieldnames = [
        "event_id",
        "n_points",
        "n_samples",
        "rms_total_path_residual_m",
        "median_sanya_snr_db",
        "median_all_snr_db",
        "first_detection_alt_km",
        "a_au_mean",
        "a_au_std",
        "e_mean",
        "e_std",
        "e_p05",
        "e_p50",
        "e_p95",
        "interstellar_fraction_e_gt_1",
        "inc_deg_mean",
        "inc_deg_std",
        "argp_deg_std",
        "node_deg_std",
        "nu_deg_std",
        "above_atmosphere_dt_s_median",
        "above_atmosphere_no_drag_dt_s_median",
        "above_atmosphere_reached_fraction",
        "above_atmosphere_no_drag_reached_fraction",
        "pre_atmosphere_speed_drag_m_s_median",
        "pre_atmosphere_speed_no_drag_m_s_median",
        "pre_atmosphere_speed_delta_m_s_median",
        "pre_atmosphere_speed_frac_diff_median",
        "pre_atmosphere_velocity_vector_frac_diff_median",
        "pre_atmosphere_position_frac_diff_median",
        "pre_atmosphere_state_reliability_flag",
        "covariance_available",
    ]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def write_h5(path: str, rows: list[dict], args) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    string_dtype = h5py.string_dtype(encoding="utf-8")
    with h5py.File(path, "w") as h:
        h.attrs["script"] = "estimate_orbit_element_uncertainty.py"
        h.attrs["input_h5"] = args.input
        h.attrs["kernel"] = args.kernel
        h.attrs["samples_per_event"] = args.samples
        h.attrs["above_atmosphere_alt_km"] = args.above_atmosphere_alt_km
        h.attrs["above_atmosphere_model"] = "Backward central-gravity plus fitted drag using a simple exponential high-atmosphere density."
        h.attrs["orbit_propagator"] = "dasst.orbit_determination.rebound_od"
        h["event_id"] = np.asarray([r["event_id"] for r in rows], dtype=string_dtype)
        for key in rows[0]:
            if key in ("event_id", "kepler_sample", "above_states_gcrs", "above_states_no_drag_gcrs"):
                continue
            h[key] = np.asarray([r[key] for r in rows])
        g = h.create_group("kepler_samples")
        ag = h.create_group("above_atmosphere_gcrs_states")
        ng = h.create_group("above_atmosphere_no_drag_gcrs_states")
        for row in rows:
            g.create_dataset(row["event_id"], data=row["kepler_sample"], compression="gzip")
            ag.create_dataset(row["event_id"], data=row["above_states_gcrs"], compression="gzip")
            ng.create_dataset(row["event_id"], data=row["above_states_no_drag_gcrs"], compression="gzip")


def distribution_row(values: np.ndarray) -> tuple[float, float, float]:
    return (
        float(np.nanpercentile(values, 25.0)),
        float(np.nanpercentile(values, 50.0)),
        float(np.nanpercentile(values, 75.0)),
    )


def write_article_table(path: str, rows: list[dict]) -> None:
    metrics = [
        ("Semi-major axis std. (AU)", "a_au_std"),
        ("Eccentricity std.", "e_std"),
        ("Inclination std. (deg)", "inc_deg_std"),
        ("Argument of perihelion std. (deg)", "argp_deg_std"),
        ("Longitude of ascending node std. (deg)", "node_deg_std"),
    ]
    lines = [
        "% Auto-generated by /Users/jvi019/src/lfm_meteor/estimate_orbit_element_uncertainty.py",
        "\\begin{tabular}{@{}lrrr@{}}",
        "\\toprule",
        "Quantity & 25\\% & Median & 75\\% \\\\",
        "\\midrule",
    ]
    for label, key in metrics:
        q25, q50, q75 = distribution_row(np.asarray([r[key] for r in rows], dtype=np.float64))
        lines.append(f"{label} & {q25:.3g} & {q50:.3g} & {q75:.3g} \\\\")
    frac = np.asarray([r["interstellar_fraction_e_gt_1"] for r in rows], dtype=np.float64)
    q25, q50, q75 = distribution_row(frac)
    lines.append(f"Monte Carlo fraction with $e>1$ & {q25:.3g} & {q50:.3g} & {q75:.3g} \\\\")
    q25, q50, q75 = distribution_row(np.asarray([r["median_sanya_snr_db"] for r in rows], dtype=np.float64))
    lines.append(f"Median Sanya SNR (dB) & {q25:.3g} & {q50:.3g} & {q75:.3g} \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--input", default=INPUT_H5)
    p.add_argument("--output-h5", default=OUTPUT_H5)
    p.add_argument("--summary-csv", default=SUMMARY_CSV)
    p.add_argument("--article-table", default=ARTICLE_TABLE)
    p.add_argument("--example-figure", default=EXAMPLE_FIGURE)
    p.add_argument("--orbit-xy-figure", default=ORBIT_XY_FIGURE)
    p.add_argument(
        "--snr-scatter-figure",
        default="/Users/jvi019/src/sanya_tristatic_paper/figures/orbit_element_uncertainty_vs_snr.pdf",
    )
    p.add_argument("--example-event-id", default=None)
    p.add_argument("--only-event-id", default=None)
    p.add_argument("--make-example-plot", action="store_true")
    p.add_argument("--make-orbit-xy-plot", action="store_true")
    p.add_argument("--make-snr-scatter-plot", action="store_true")
    p.add_argument("--kernel", default=DEFAULT_KERNEL)
    p.add_argument("--samples", type=int, default=100)
    p.add_argument("--start-index", type=int, default=0)
    p.add_argument("--max-events", type=int, default=None)
    p.add_argument("--seed", type=int, default=20260614)
    p.add_argument("--above-atmosphere-alt-km", type=float, default=200.0)
    p.add_argument("--max-back-s", type=float, default=20.0)
    p.add_argument("--rebound-dt-s", type=float, default=10.0)
    p.add_argument("--rebound-max-t-s", type=float, default=7 * 24 * 3600.0)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    rng = np.random.default_rng(args.seed)
    fits = [fit for fit in load_fits(args.input) if fit.covariance_available]
    if args.only_event_id is not None:
        fits = [fit for fit in fits if fit.event_id == args.only_event_id]
    if args.start_index:
        fits = fits[args.start_index :]
    if args.max_events is not None:
        fits = fits[: args.max_events]
    if not fits:
        raise RuntimeError("No covariance-bearing fits found.")

    rows = []
    for idx, fit in enumerate(fits):
        print(f"[{idx + 1}/{len(fits)}] {fit.event_id}", flush=True)
        rows.append(process_event(fit, args, rng))

    write_summary_csv(args.summary_csv, rows)
    write_h5(args.output_h5, rows, args)
    write_article_table(args.article_table, rows)
    if args.make_example_plot:
        example = rows[0]
        if args.example_event_id is not None:
            matches = [row for row in rows if row["event_id"] == args.example_event_id]
            if matches:
                example = matches[0]
        make_example_plot(example, args.example_figure)
        print(f"wrote {args.example_figure}")
        print(f"wrote {os.path.splitext(args.example_figure)[0] + '.png'}")
    if args.make_snr_scatter_plot:
        make_snr_scatter_plot(rows, args.snr_scatter_figure)
        print(f"wrote {args.snr_scatter_figure}")
        print(f"wrote {os.path.splitext(args.snr_scatter_figure)[0] + '.png'}")
    if args.make_orbit_xy_plot:
        example = rows[0]
        if args.example_event_id is not None:
            matches = [row for row in rows if row["event_id"] == args.example_event_id]
            if matches:
                example = matches[0]
        make_orbit_xy_plot(example, args.orbit_xy_figure)
        print(f"wrote {args.orbit_xy_figure}")
        print(f"wrote {os.path.splitext(args.orbit_xy_figure)[0] + '.png'}")
    print(f"wrote {args.summary_csv}")
    print(f"wrote {args.output_h5}")
    print(f"wrote {args.article_table}")


if __name__ == "__main__":
    main()
