#!/usr/bin/env python3
"""Estimate fitted tri-static yield in the dawn/apex local-time window."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

import h5py
import numpy as np


INPUT_H5 = Path("results/all_tristatic_ballistic_snr_weighted_v20260613b.h5")
OUTPUT_TEX = Path("/Users/jvi019/src/sanya_tristatic_paper/tables/dawn_window_yield_macros.tex")
LOCAL_OFFSET_HOURS = 8
WINDOW_CENTER_LOCAL_HOUR = 6.0
WINDOW_HALF_WIDTH_HOURS = 4.0


def local_hour(dt_utc: datetime) -> float:
    local = dt_utc.astimezone(timezone(timedelta(hours=LOCAL_OFFSET_HOURS)))
    return local.hour + local.minute / 60.0 + local.second / 3600.0


def main() -> None:
    with h5py.File(INPUT_H5, "r") as h:
        t0_ns = np.asarray(h["t0_ns"][:], dtype=np.int64)

    utc_times = [datetime.fromtimestamp(int(t) / 1e9, tz=timezone.utc) for t in t0_ns]
    local_times = [t.astimezone(timezone(timedelta(hours=LOCAL_OFFSET_HOURS))) for t in utc_times]
    lower = WINDOW_CENTER_LOCAL_HOUR - WINDOW_HALF_WIDTH_HOURS
    upper = WINDOW_CENTER_LOCAL_HOUR + WINDOW_HALF_WIDTH_HOURS
    in_window = np.asarray([lower <= local_hour(t) < upper for t in utc_times], dtype=bool)

    # The experiment only overlaps the 02--10 local-time window from 02:00 to
    # the last fitted event at 07:49 local time, so use the observed overlap
    # rather than the full eight-hour recommendation window.
    overlap_start = datetime(
        local_times[-1].year,
        local_times[-1].month,
        local_times[-1].day,
        int(lower),
        0,
        0,
        tzinfo=timezone(timedelta(hours=LOCAL_OFFSET_HOURS)),
    )
    overlap_end = max(local_times)
    overlap_hours = (overlap_end - overlap_start).total_seconds() / 3600.0
    count = int(np.sum(in_window))
    rate_per_hour = count / overlap_hours
    minutes_per_fit = 60.0 / rate_per_hour
    one_sixtieth_rate_per_elapsed_hour = rate_per_hour / 60.0

    OUTPUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_TEX.write_text(
        "\n".join(
            [
                "% Generated by /Users/jvi019/src/lfm_meteor/estimate_dawn_observing_window_yield.py",
                rf"\newcommand{{\dawnWindowFitCount}}{{{count}}}",
                rf"\newcommand{{\dawnWindowOverlapHours}}{{{overlap_hours:.2f}}}",
                rf"\newcommand{{\dawnWindowFitRatePerHour}}{{{rate_per_hour:.1f}}}",
                rf"\newcommand{{\dawnWindowMinutesPerFit}}{{{minutes_per_fit:.1f}}}",
                rf"\newcommand{{\dawnWindowOneSixtiethRatePerElapsedHour}}{{{one_sixtieth_rate_per_elapsed_hour:.2f}}}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT_TEX}")
    print(f"count={count}")
    print(f"overlap_hours={overlap_hours:.6f}")
    print(f"rate_per_hour={rate_per_hour:.6f}")
    print(f"minutes_per_fit={minutes_per_fit:.6f}")
    print(f"one_sixtieth_rate_per_elapsed_hour={one_sixtieth_rate_per_elapsed_hour:.6f}")


if __name__ == "__main__":
    main()
