#!/usr/bin/env python3
"""Estimate fitted tri-static event durations from the ballistic product."""

from __future__ import annotations

from pathlib import Path

import h5py
import numpy as np


INPUT_H5 = Path("results/all_tristatic_ballistic_snr_weighted_v20260613b.h5")
OUTPUT_TEX = Path("/Users/jvi019/src/sanya_tristatic_paper/tables/tristatic_event_duration_macros.tex")


def load_durations_s(path: Path) -> np.ndarray:
    durations = []
    with h5py.File(path, "r") as h:
        for event_id in h["points"]:
            group = h["points"][event_id]
            if "t_rel_s" in group:
                t_rel_s = np.asarray(group["t_rel_s"][:], dtype=float)
            else:
                time_ns = np.asarray(group["time_ns"][:], dtype=np.int64)
                t_rel_s = (time_ns - time_ns[0]) * 1e-9
            if t_rel_s.size > 1:
                durations.append(float(np.nanmax(t_rel_s) - np.nanmin(t_rel_s)))
    return np.asarray(durations, dtype=float)


def write_macros(path: Path, durations_s: np.ndarray) -> None:
    mean_s = float(np.nanmean(durations_s))
    median_s = float(np.nanmedian(durations_s))
    p95_s = float(np.nanpercentile(durations_s, 95.0))
    n = int(np.sum(np.isfinite(durations_s)))
    text = "\n".join(
        [
            "% Generated by /Users/jvi019/src/lfm_meteor/estimate_tristatic_event_durations.py",
            rf"\newcommand{{\tristaticEventDurationN}}{{{n}}}",
            rf"\newcommand{{\tristaticEventDurationMeanS}}{{{mean_s:.3f}}}",
            rf"\newcommand{{\tristaticEventDurationMedianS}}{{{median_s:.3f}}}",
            rf"\newcommand{{\tristaticEventDurationPninetyfiveS}}{{{p95_s:.3f}}}",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> None:
    durations_s = load_durations_s(INPUT_H5)
    write_macros(OUTPUT_TEX, durations_s)
    print(f"Wrote {OUTPUT_TEX}")
    print(f"n={len(durations_s)}")
    print(f"mean_s={np.nanmean(durations_s):.6f}")
    print(f"median_s={np.nanmedian(durations_s):.6f}")
    print(f"p95_s={np.nanpercentile(durations_s, 95.0):.6f}")


if __name__ == "__main__":
    main()
